name: Main Branch CI
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          swift test --enable-code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./.build/debug/codecov/WebsocketKit.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true    
  update_documentation:
    name: Update documentation
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: WebSocketKit
          output: "docs"
          format: "html"
          base-url: "https://alexanderwe.github.io/WebSocketKit"
      - name: Commit documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/**
          git commit -m "Generate documentation"
          git push
